capitales_estados_mexico = {'Aguascalientes':'Aguascalientes',
                            'Baja California':'Mexicali',
                            'Baja California Sur':'La Paz',
                            'Campeche':'San Francisco de Campeche',
                            'Chiapas':'Tuxtla Gutiérrez',
                            'Chihuahua':'Chihuahua',
                            'Coahuila de Zaragoza':'Saltillo',
                            'Colima':'Colima',
                            'Durango':'Victoria de Durango',
                            'Estado de México':'Toluca de Lerdo',
                            'Guanajuato':'Guanajuato',
                            'Guerrero':'Chilpancingo de los Bravo',
                            'Hidalgo':'Pachuca de Soto',
                            'Jalisco':'Guadalajara',
                            'Michoacán de Ocampo':'Morelia',
                            'Morelos':'Cuernavaca',
                            'Nayarit':'Tepic',
                            'Nuevo León':'Monterrey',
                            'Oaxaca':'Oaxaca de Juárez',
                            'Puebla':'Puebla de Zaragoza',
                            'Querétaro':'Santiago de Querétaro',
                            'Quintana Roo':'Chetumal',
                            'San Luis Potosí':'San Luis Potosí',
                            'Sinaloa':'Culiacán Rosales',
                            'Sonora':'Hermosillo',
                            'Tabasco':'Villahermosa',
                            'Tamaulipas':'Ciudad Victoria',
                            'Tlaxcala':'Tlaxcala de Xicohténcatl',
                            'Veracruz de Ignacio de la Llave':'Xalapa-Enríquez',
                            'Yucatán':'Mérida',
                            'Zacatecas':'Zacatecas'}
